services:
  mapproxy:
    image: ghcr.io/mapproxy/mapproxy/mapproxy:1.16.0-nginx
    # image is amd64-only; force emulation on arm64 hosts (e.g. Apple Silicon)
    platform: linux/amd64
    volumes:
      - ./mapproxy.yaml:/mapproxy/config/mapproxy.yaml
      # cache_data needs to be writable by the container
      - ./cache_data:/mapproxy/config/cache_data
    ports:
      # demo: http://localhost:8080/mapproxy/demo/
      - "8080:80"
    restart: unless-stopped
